global_home: /home/rise/lavanya/microtest_new/microtesk-riscv-0.1.0-beta-191227
global_config_path: /home/rise/lavanya/gitlab/shakti/verif/iclass-verif/core_block/microtesk/templates
global_command: generate.sh riscv
global_args: --solver z3 --generate
global_output: ./workdir/
global_seed: random
global_jobs: 1
global_count: 1

rv32d_mentry_fadd_d:
  path: floating

rv32f_mentry_fadd_s:
  path: floating
#branch_fixed:
#  path: examples/branches
###branch_merge:
###  path: examples/branches
###branch_specs:
###  path: examples/branches
###
#selfcheck:
#  path: examples/selfcheck
#  args: --self-checks
#ld:
#  path: compliance/rv64ui
#add:
#  path: compliance/rv64ui
###
###register:
###  path: examples/registers
###register_allocation:
###  path: examples/registers
###register_exclude_retain:
###  path: examples/registers
###register_reservation_auto:
###  path: examples/registers
###register_reservation_manual:
###  path: examples/registers
###
###numeric_label:
###  path: examples/labels
###numeric_label_random:
###  path: examples/labels
###weak_symbol:
###  path: examples/labels
###
###preparator:
###  path: examples/preparators
###
###arithmetic:
###  path: examples/sequences
###atomic:
###  path: examples/sequences
###block:
###  path: examples/sequences
###group:
###  path: examples/sequences
###iterate:
###  path: examples/sequences
###nitems:
###  path: examples/sequences
###sequence:
###  path: examples/sequences
###
###boundary_data:
###  path: examples/testdata
###random:
###  path: examples/testdata
###situation:
###  path: examples/testdata
###testdata:
###  path: examples/testdata
###
###int_divide:
###  path: algorithms/integer
###int_euclid:
###  path: algorithms/integer
#int_minmax:
#  path: algorithms/integer
###int_sqrt:
###  path: algorithms/integer
###
###bubblesort_byte:
###  path: algorithms/sorting
###bubblesort_hword:
###  path: algorithms/sorting
###bubblesort_word:
###  path: algorithms/sorting
###
###simple_auto:
###  path: autogen
###boundary_auto:
###  path: autogen
###group_auto:
###  path: autogen
####sequence_auto:
####  path: autogen
###
###debug_jalr:
###  path: debug
###debug_la:
###  path: debug
###debug_ld_sd:
###  path: debug
###debug_ld_sd_sv39:
###  path: debug
###debug_ld_sd_sv48:
###  path: debug
###debug_li:
###  path: debug
###debug_lw_sw:
###  path: debug
###debug_lw_sw_sv32:
###  path: debug
###debug_rv32a:
###  path: debug
###debug_rv32d:
###  path: debug
###debug_rv32f:
###  path: debug
###debug_rv32f2:
###  path: debug
###debug_rv32i:
###  path: debug
###debug_rv32m:
###  path: debug
###debug_rv32v:
###  path: debug
###debug_rv64a:
###  path: debug
###debug_rv64d:
###  path: debug
###debug_rv64f:
###  path: debug
###debug_rv64i:
###  path: debug
###debug_rv64m:
###  path: debug
###debug_rvc:
###  path: debug
###
###seq_xxx:
###  path: synthetics/rvxxx
