stages:
  - build
  - doc

river_core:
  stage: build
  script:
    - cd tests
    - pytest test_river_core.py -v
  only:
    refs:
      - master
  tags:
    - incore-group
  except:
    - schedules

doc:
  stage: doc
  script:
    - cd docs
    - make latexpdf
    - cd ..
    - cp docs/build/latex/river_core.pdf .
  only:
    refs:
      - master
  artifacts:
    name: river_core
    paths: 
      - ./river_core.pdf
  tags:
    - incore-group
