global_home: 
global_config_path: /aapg_plugin/
global_command: aapg gen 
global_args:
global_output: ${OUTPUT_DIR}/aapg
global_seed: random
global_jobs: 1
global_count: 2

config1:
  path: templates
exceptions:
  path: templates
illegal:
  path: templates
rv32ic_bringup:
  path: templates
rv32imac_bringup:
  path: templates
rv32imaf_bringup:
  path: templates
rv32imafc_bringup:
  path: templates
rv32imc_bringup:
  path: templates
rv64ic_bringup:
  path: templates
rv64imac_bringup:
  path: templates
rv64imafd_bringup:
  path: templates
rv64imafdc_branches1:
  path: templates
rv64imafdc_bringup:
  path: templates
rv64imafdc_exceptions:
  path: templates
rv64imafdc_hazards:
  path: templates
rv64imafdc_illegal:
  path: templates
rv64imafdc_user:
  path: templates
rv64imafd_exceptions:
  path: templates
rv64imc_bringup:
  path: templates
v_bringup:
  path: templates
