isa: rv64imafdc
abi: lp64
gcc:
  command: riscv64-unknown-elf-gcc
  args: -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -DENTROPY=0x9629af2 -std=gnu99 -O2
spike:
  command: 'spike -c'
disass:
  command: 'riscv64-unknown-elf-objdump -D'
elf2hex:
  command: elf2hex
  args: [16, 131072, 2147483648]
  out_file: code.mem
sim:
  command: ./out
  args: +rtldump
extras_1:
  command: 'ln -sf /home/rise/lavanya/gitlab/shakti/cores/i-class/base-sim/bin/out .'
extras_2:
  command: 'ln -sf /home/rise/lavanya/gitlab/shakti/cores/i-class/base-sim/bin/bootfile .'
extras_3:
  command: head -n -4 rtl.dump
  out_file: temp.dump
extras_4:
  command: mv temp.dump rtl.dump
order:
  - 'gcc'
  - 'spike'
  - 'disass'
  - 'elf2hex'
  - 'extras_1'
  - 'extras_2'
  - 'sim'
  - 'extras_3'
  - 'extras_4'

  
